apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: debug
  template:
    metadata:
      labels:
        k8s-app: debug
    spec:
      serviceAccountName: coredns
      containers:
      - name: debug
        image: docker.henkel.wtf/hcloud/debug:1
        imagePullPolicy: Always
        command: ["tail", "-f", "/dev/null"]
      dnsPolicy: Default