# Calico Version v3.11.1
# https://docs.projectcalico.org/v3.11/releases#v3.11.1
# This manifest includes the following component versions:
#   calico/kube-controllers:v3.11.1

# Create this manifest using kubectl to deploy
# the Calico Kubernetes controllers.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  # Only a single instance of the this pod should be
  # active at a time.  Since this pod is run as a Deployment,
  # Kubernetes will ensure the pod is recreated in case of failure,
  # removing the need for passive backups.
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
  template:
    metadata:
      name: calico-kube-controllers
      namespace: kube-system
      labels:
        k8s-app: calico-kube-controllers
    spec:
      serviceAccountName: calico-kube-controllers
      volumes:
        - name: calico-etcd-certs
          secret:
            secretName: calico-etcd-certs
      hostNetwork: true
      containers:
        - name: calico-kube-controllers
          # Make sure to pin this to your desired version.
          image: calico/kube-controllers:v3.11.1
          env:
            # Configure the location of your etcd cluster.
            - name: ETCD_ENDPOINTS
              value: "https://10.0.1.50:2379,https://10.0.1.51:2379,https://10.0.1.52:2379"
            - name: ETCD_CA_CERT_FILE
              value: "/calico-etcd-certs/ca.pem"
            - name: ETCD_CERT_FILE
              value: "/calico-etcd-certs/kubernetes.pem"
            - name: ETCD_KEY_FILE
              value: "/calico-etcd-certs/kubernetes-key.pem"
          volumeMounts:
            - name: calico-etcd-certs
              mountPath: "/calico-etcd-certs"
              readOnly: true
